### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by Smiley98** [ianw3214/bananana-server#1]
Python has a really bad runtime. 0/10 would not recommend.
For MAXIMUM speed, check out https://github.com/Smiley98/Asynchronous-Socket-Text-Chat
It uses a real language and a real socket programming API <3
Also use the Air_Hockey branch cause I'm too lazy to re-merge into master for my school assignments.

**Comment by ianw3214** [comment]
Haha I use Python so I can deploy easily, or else I would've gone with c++ xD
